<?php

$_LANG['token'] = ', Error Token:';
$_LANG['generalError'] = 'Something has gone wrong. Check the logs and contact the administrator';

$_LANG['addonAA']['datatables']['next'] = 'Next';
$_LANG['addonAA']['datatables']['previous'] = 'Next';
$_LANG['addonAA']['datatables']['zeroRecords'] = 'Nothing to display';

$_LANG['addonAA']['pagesLabels']['home']['label']          = 'main';

$_LANG['addonAA']['pagesLabels']['home']['boxes']          = 'Boxes';
$_LANG['addonAA']['pagesLabels']['home']['buttons']        = 'Buttons';
$_LANG['addonAA']['pagesLabels']['home']['formAdvanced']   = 'Form Advanced';
$_LANG['addonAA']['pagesLabels']['home']['formGeneral']    = 'Form General';
$_LANG['addonAA']['pagesLabels']['home']['icons']          = 'Icons';
$_LANG['addonAA']['pagesLabels']['home']['panels']         = 'Panels';
$_LANG['addonAA']['pagesLabels']['home']['tableAjax']      = 'Table Ajax';
$_LANG['addonAA']['pagesLabels']['home']['tableResponsive']= 'Table Responsive';
$_LANG['addonAA']['pagesLabels']['home']['tables']         = 'Tables';
$_LANG['addonAA']['pagesLabels']['home']['typography']     = 'Typography';

$_LANG['addonAA']['pagesLabels']['testPage']['label']         = 'Test Page';
$_LANG['addonAA']['pagesLabels']['testPageSimple']['label']   = 'Simple Page';
$_LANG['addonAA']['pagesLabels']['whmcsMagic']['label']       = 'WHMCS Magic';
$_LANG['addonAA']['pagesLabels']['whmcsServices']['label']    = 'WHMCS SErev';

$_LANG['addonAA']['whmcsServices']['table']['name'] = 'whmcsServices table name';
$_LANG['addonAA']['whmcsServices']['item']['id']['label'] = 'item id label';
$_LANG['addonAA']['whmcsServices']['item']['type']['label'] = 'item type label';
$_LANG['addonAA']['whmcsServices']['item']['group']['label'] = 'item group label';
$_LANG['addonAA']['whmcsServices']['item']['name']['label'] = 'item name label';
$_LANG['addonAA']['whmcsServices']['item']['server_type']['label'] = 'item server_type label';
$_LANG['addonAA']['whmcsServices']['item']['server_group_id']['label'] = 'item server_group_id label';
$_LANG['addonAA']['whmcsServices']['item']['actions']['label'] = 'item actions label';
$_LANG['addonAA']['whmcsServices']['modal']['editLabel'] = 'whmcsServices modal editLabel';
$_LANG['addonAA']['whmcsServices']['modal']['close'] = 'whmcsServices modal close';
$_LANG['addonAA']['whmcsServices']['modal']['updateItem'] = 'whmcsServices modal updateItem';
$_LANG['addonAA']['whmcsServices']['modal']['deleteLabel'] = 'whmcsServices modal deleteLabel';
$_LANG['addonAA']['whmcsServices']['modal']['deleteDescription'] = 'whmcsServices modal deleteDescription';
$_LANG['addonAA']['whmcsServices']['modal']['delete'] = 'whmcsServices modal delete';


$_LANG['addonAA']['whmcsServices']['actionButtons']['customfields'] = 'customfields';
$_LANG['addonAA']['whmcsServices']['actionButtons']['configoptions'] = 'configoptions';
$_LANG['addonAA']['whmcsServices']['actionButtons']['edit'] = 'edit';
$_LANG['addonAA']['whmcsServices']['actionButtons']['delete'] = 'delete';

$_LANG['addonAA']['pagesLabels']['servers']['label'] = 'Servers';
$_LANG['addonAA']['pagesLabels']['servers']['list'] = 'Servers List';
$_LANG['addonAA']['pagesLabels']['servers']['vmList'] = 'VMs List';
$_LANG['addonAA']['pagesLabels']['servers']['settings'] = 'Default Settings';
$_LANG['addonAA']['pagesLabels']['ipManagement']['label'] = 'IP Management';
$_LANG['addonAA']['pagesLabels']['clusters']['label'] = 'Clusters';
$_LANG['addonAA']['pagesLabels']['templates']['label'] = 'Templates';
$_LANG['addonAA']['pagesLabels']['templates']['list'] = 'Templates List ';
$_LANG['addonAA']['pagesLabels']['templates']['create'] = 'Create Template';
$_LANG['addonAA']['pagesLabels']['vmCleaner']['label'] = 'VM Cleaner';
$_LANG['addonAA']['pagesLabels']['documentation']['label'] = 'Documentation';
$_LANG['addonAA']['pagesLabels']['documentation']['proxmoxVPS'] = 'Proxmox VPS For WHMCS';
$_LANG['addonAA']['pagesLabels']['documentation']['proxmoxCloud'] = 'Proxmox Cloud For WHMCS';


$_LANG['generalError'] = "Something has gone wrong. Check the logs and contact the administrator";
$_LANG['token'] = " Token ";

$_LANG['subPagesTitles']['documentation']['proxmoxVPS'] = 'Proxmox VPS For WHMCS';
$_LANG['subPagesTitles']['documentation']['proxmoxCloud'] = 'Proxmox Cloud For WHMCS';

$_LANG['addonAA']['clusters']['header']['clusters'] = 'Clusters';
$_LANG['addonAA']['clusters']['search'] = 'Search';

$_LANG['addonAA']['clusters']['filters']['server'] = 'Server';
$_LANG['addonAA']['clusters']['filters']['Filter'] = 'Filter';
$_LANG['addonAA']['clusters']['tableHeader']['Name'] = 'Name';
$_LANG['addonAA']['clusters']['tableHeader']['Uptime'] = 'Uptime';
$_LANG['addonAA']['clusters']['tableHeader']['CPU'] = 'CPU';
$_LANG['addonAA']['clusters']['tableHeader']['CPU Usage'] = 'CPU Usage';
$_LANG['addonAA']['clusters']['tableHeader']['SWAP Usage'] = 'SWAP Usage';
$_LANG['addonAA']['clusters']['tableHeader']['Memory Usage'] = 'Memory Usage';
$_LANG['addonAA']['clusters']['tableHeader']['Disk Usage'] = 'Disk Usage';
$_LANG['addonAA']['clusters']['noClientAvailable']='No Server Available';
$_LANG['addonAA']['clusters']['noClientAvailableInfo']='';
$_LANG['addonAA']['clusters']['previous']='Previous';
$_LANG['addonAA']['clusters']['next']='Next';
$_LANG['addonAA']['clusters']['header']['summary']='Summary'; 
$_LANG['addonAA']['clusters']['uptime']='Uptime';
$_LANG['addonAA']['clusters']['loadAverage'] = 'Load Average';
$_LANG['addonAA']['clusters']['cpus'] = 'CPUs';
$_LANG['addonAA']['clusters']['cpusUsage'] = 'CPUs Usage';
$_LANG['addonAA']['clusters']['sockets'] = 'Sockets';
$_LANG['addonAA']['clusters']['socket'] = 'Socket';
$_LANG['addonAA']['clusters']['total'] = 'Total: ';
$_LANG['addonAA']['clusters']['used'] = 'Used: ';
$_LANG['addonAA']['clusters']['free'] = 'Free: ';
$_LANG['addonAA']['clusters']['ramUsage'] = 'RAM Usage';
$_LANG['addonAA']['clusters']['ramUsage'] = 'RAM Usage';
$_LANG['addonAA']['clusters']['ioDelay'] = 'IO Delay';
$_LANG['addonAA']['clusters']['swapUsage'] = 'SWAP Usage';
$_LANG['addonAA']['clusters']['KSMSharing'] = 'KSM Sharing';
$_LANG['addonAA']['clusters']['HDSpace(root)'] = 'HD Space (root)';
$_LANG['addonAA']['clusters']['PVEManagerVersion'] = 'PVE Manager Version';
$_LANG['addonAA']['clusters']['Kernel Version'] = 'Kernel Version';
$_LANG['addonAA']['clusters']['header']['subscription'] = 'Subscription';
$_LANG['addonAA']['clusters']['status'] = 'Status';
$_LANG['addonAA']['clusters']['serverId'] = 'Server ID';
$_LANG['addonAA']['clusters']['header']['Graphs'] = 'Graphs';
$_LANG['addonAA']['clusters']['Hour']='Hour';
$_LANG['addonAA']['clusters']['Day']='Day';
$_LANG['addonAA']['clusters']['Week']='Week';
$_LANG['addonAA']['clusters']['Month']='Month';
$_LANG['addonAA']['clusters']['Year']='Year';
$_LANG['addonAA']['clusters']['CPU usage %']='CPU usage %';
$_LANG['addonAA']['clusters']['Memory Usage']='Memory Usage';
$_LANG['addonAA']['clusters']['Network Traffic']='Network Traffic';
$_LANG['addonAA']['clusters']['Disk IO']='Disk IO';
$_LANG['addonAA']['clusters']['Server Load']='Server Load';

$_LANG['subPagesTitles']['templates']['list'] = 'List';
$_LANG['subPagesTitles']['templates']['create'] = 'Create';
$_LANG['addonAA']['templates']['filters']['server'] = 'Server';
$_LANG['addonAA']['templates']['filters']['Filter'] = 'Filter';
$_LANG['addonAA']['templates']['search'] = 'Search';
$_LANG['addonAA']['templates']['previous'] = 'Previous';
$_LANG['addonAA']['templates']['next'] = 'Next';
$_LANG['addonAA']['templates']['noAvailable'] = 'Not Available';
$_LANG['addonAA']['templates']['noAvailableInfo'] = '';
$_LANG['addonAA']['templates']['header']['Templates'] = 'Templates';
$_LANG['addonAA']['templates']['tableHeader']['Node'] = 'Node';
$_LANG['addonAA']['templates']['tableHeader']['VMID'] = 'VMID';
$_LANG['addonAA']['templates']['tableHeader']['Name'] = 'Name';
$_LANG['addonAA']['templates']['tableHeader']['Description'] = 'Description';
$_LANG['addonAA']['templates']['tableHeader']['OS Type'] = 'OS Type';
$_LANG['addonAA']['templates']['tableHeader']['Action']='Action';
$_LANG['addonAA']['templates']['modal']['deleteLabel2']='Delete: '; 
$_LANG['addonAA']['templates']['modal']['delete']='Delete';
$_LANG['addonAA']['templates']['modal']['close']='Close';
$_LANG['addonAA']['templates']['modal']['deleteOne']='Are you sure that you want to delete this entry from the templates list? '; 
$_LANG['addonAA']['templates']['messages']['deleteSuccess']='The template %s has been deleted successfully';
$_LANG['addonAA']['templates']['header']['Create Template']='Create Template';
$_LANG['addonAA']['templates']['button']['Next Step']='Next Step';
$_LANG['addonAA']['templates']['VM will be converted to a template.']='The virtual machine will be converted to a template.';
$_LANG['addonAA']['templates']['Node']='Node';
$_LANG['addonAA']['templates']['VM']='VM';
$_LANG['addonAA']['templates']['Template Friendly Name']='Template Friendly Name';
$_LANG['addonAA']['templates']['button']['Save Changes']='Save Changes';
$_LANG['addonAA']['templates']['Template has been created successfully']='The template has been created successfully';
$_LANG['addonAA']['templates']['You have not selected a node']='You need to select the node';
$_LANG['addonAA']['templates']['You have not selected a vmid']='You need to select the VMID';

$_LANG['addonAA']['settings']['filters']['server']='Server';
$_LANG['addonAA']['settings']['filters']['Filter']='Filter';
$_LANG['addonAA']['settings']['tableHeader']['Node']='Node';
$_LANG['addonAA']['settings']['tableHeader']['VMID']='VMID';
$_LANG['addonAA']['settings']['tableHeader']['Name']='Name';
$_LANG['addonAA']['settings']['tableHeader']['Type']='Type';
$_LANG['addonAA']['settings']['tableHeader']['Status']='Status';
$_LANG['addonAA']['settings']['tableHeader']['Action']='Action';
$_LANG['addonAA']['settings']['noAvailable']='Not Available';
$_LANG['addonAA']['settings']['noAvailableInfo']='';
$_LANG['addonAA']['settings']['search']='Search';
$_LANG['addonAA']['settings']['previous']='Previous';
$_LANG['addonAA']['settings']['next']='Next';
$_LANG['addonAA']['settings']['actionButtons']['delete']='Delete';
$_LANG['addonAA']['settings']['modal']['deleteLabel2']='Delete VM: '; 
$_LANG['addonAA']['settings']['modal']['deleteOne']='Are you sure that you want to remove this virtual machine? This action will permanently erase all the VM data.'; 
$_LANG['addonAA']['settings']['modal']['delete']='Delete';
$_LANG['addonAA']['settings']['modal']['close']='Close';
$_LANG['addonAA']['settings']['Removing VM %s in progress..']='The VM removing %s is in progress';
$_LANG['addonAA']['ipManagement']['filters']['server']='Server'; 
$_LANG['addonAA']['ipManagement']['filters']['Reset']='Reset';
$_LANG['addonAA']['ipManagement']['filters']['Filter']='Filter';
$_LANG['addonAA']['ipManagement']['search']='Search';
$_LANG['addonAA']['ipManagement']['filters']['toggle']='Toggle Filter';
$_LANG['addonAA']['ipManagement']['filters']['IP Address']='IP Address';
$_LANG['addonAA']['ipManagement']['filters']['filter-ip-placeholder']='Filter IP';
$_LANG['addonAA']['ipManagement']['filters']['MAC Address']='MAC Address';
$_LANG['addonAA']['ipManagement']['filters']['filter-mac-placeholder']='Filter MAC';
$_LANG['addonAA']['ipManagement']['tableHeader']['IP Address']='IP Address';
$_LANG['addonAA']['ipManagement']['tableHeader']['MAC Address']='MAC Address';
$_LANG['addonAA']['ipManagement']['tableHeader']['Subnet Mask']='Subnet Mask';
$_LANG['addonAA']['ipManagement']['tableHeader']['Gateway']='Gateway';
$_LANG['addonAA']['ipManagement']['tableHeader']['Server']='Server';
$_LANG['addonAA']['ipManagement']['tableHeader']['Virtualization']='Virtualization';
$_LANG['addonAA']['ipManagement']['tableHeader']['Action']='Actions';
$_LANG['addonAA']['ipManagement']['noAvailable']='Not Available';
$_LANG['addonAA']['ipManagement']['noAvailableInfo']='';
$_LANG['addonAA']['ipManagement']['previous']='Previous';
$_LANG['addonAA']['ipManagement']['next']='Next';
$_LANG['addonAA']['ipManagement']['button']['New IP Addresses']='New IP Addresses'; 

$_LANG['addonAA']['ipManagement']['modal']['add']='New IP Addresses'; 
$_LANG['addonAA']['ipManagement']['newIP']['pool']['label']='IP Pool';
$_LANG['addonAA']['ipManagement']['newIP']['pool']['description']='';
$_LANG['addonAA']['ipManagement']['newIP']['mask']['label']='Mask';
$_LANG['addonAA']['ipManagement']['newIP']['mask']['description']='In case of IPv6 addresses, make sure that you have changed the net mask.';
$_LANG['addonAA']['ipManagement']['modal']['Add IP Addresses']='Add';
$_LANG['addonAA']['ipManagement']['modal']['close']='Close';
$_LANG['addonAA']['ipManagement']['newIP']['mac']['description']='[XX:XX:XX:XX:XX:XX] should be unique.';
$_LANG['addonAA']['ipManagement']['newIP']['subnetMask']['label']='Subnet Mask';
$_LANG['addonAA']['ipManagement']['newIP']['gateway']['label']='Gateway';
$_LANG['addonAA']['ipManagement']['newIP']['server']['label']='Server';
$_LANG['addonAA']['ipManagement']['newIP']['mac']['label']='MAC Address';
$_LANG['addonAA']['ipManagement']['newIP']['trunks']['label']='VLAN Trunks';
$_LANG['addonAA']['ipManagement']['newIP']['server']['description']='';
$_LANG['addonAA']['ipManagement']['Any']='Any'; 
$_LANG['addonAA']['ipManagement']['newIP']['pool']['placeholder']='23.20.10.23';
$_LANG['addonAA']['ipManagement']['newIP']['mask']['placeholder']='24';
$_LANG['addonAA']['ipManagement']['newIP']['mac']['placeholder']='XX:XX:XX:XX:XX:XX';
$_LANG['addonAA']['ipManagement']['newIP']['virtualization']['label']='Virtualization';
$_LANG['addonAA']['ipManagement']['newIP']['virtualization']['options']['Auto']='Auto';
$_LANG['addonAA']['ipManagement']['newIP']['virtualization']['options']['KVM']='KVM';
$_LANG['addonAA']['ipManagement']['IP Address is not private'] = 'The IP address is not private';
$_LANG['addonAA']['ipManagement']['modal']['deleteLabel2']='Delete: '; 
$_LANG['addonAA']['ipManagement']['modal']['deleteOne']='Are you sure that you want to delete the selected IP addresses?'; 
$_LANG['addonAA']['ipManagement']['actionButtons']['delete']='Delete';
$_LANG['addonAA']['ipManagement']['modal']['delete']='Delete';
$_LANG['addonAA']['ipManagement']['IP Address %s has been deleted']='The IP address %s has been deleted successfully';
$_LANG['addonAA']['ipManagement']['button']['Delete']='Delete';
$_LANG['addonAA']['ipManagement']['modal']['Delete IP Addresses']='Delete IP Addresses'; 
$_LANG['addonAA']['ipManagement']['modal']['deleteAll']='Are you sure that you want to delete the selected IP addresses? '; 
$_LANG['addonAA']['ipManagement']['Selected IP Addresses have been deleted']='The selected IP addresses have been deleted successfully';
$_LANG['addonAA']['ipManagement']['Pool address has been added']='The pool has been added successfully';
$_LANG['addonAA']['ipManagement']['IP Address is not valid']='The IP address is not valid';
$_LANG['addonAA']['ipManagement']['Invalid MAC Address: %s']='Invalid MAC Address: %s';
$_LANG['addonAA']['ipManagement']['filters']['IP Version']='IP Version';
$_LANG['addonAA']['ipManagement']['filters']['IPv4']='IPv4';
$_LANG['addonAA']['ipManagement']['filters']['IPv6']='IPv6';
$_LANG['addonAA']['ipManagement']['header']['IP Management']='IP Management';
$_LANG['addonAA']['ipManagement']['modal']['Edit']='Edit:'; 
$_LANG['addonAA']['ipManagement']['editIP']['ip']['label']='IP Address';
$_LANG['addonAA']['ipManagement']['editIP']['subnetMask']['label']='Subnet Mask';
$_LANG['addonAA']['ipManagement']['editIP']['ip']['description']='';
$_LANG['addonAA']['ipManagement']['editIP']['macAddress']['label']='MAC Address';
$_LANG['addonAA']['ipManagement']['editIP']['trunks']['label']='VLAN Trunks';
$_LANG['addonAA']['ipManagement']['editIP']['gateway']['label']='Gateway';
$_LANG['addonAA']['ipManagement']['editIP']['serverID']['label']='Server';
$_LANG['addonAA']['ipManagement']['editIP']['serverID']['description']='';
$_LANG['addonAA']['ipManagement']['editIP']['visualization']['label']='Virtualization';
$_LANG['addonAA']['ipManagement']['editIP']['visualization']['options']['Auto']='Auto';
$_LANG['addonAA']['ipManagement']['editIP']['visualization']['options']['OpenVZ']='OpenVZ';
$_LANG['addonAA']['ipManagement']['editIP']['visualization']['options']['KVM']='KVM';
$_LANG['addonAA']['ipManagement']['editIP']['macAddress']['description']='';
$_LANG['addonAA']['ipManagement']['actionButtons']['edit']='Edit';
$_LANG['addonAA']['ipManagement']['modal']['Save']='Save';
$_LANG['addonAA']['ipManagement']['messages']['editSuccess']='The IP address %s has been edited successfully';
$_LANG['addonAA']['ipManagement']['filters']['IP Type'] = 'IP Type';
$_LANG['addonAA']['ipManagement']['filters']['Public'] = 'Public';
$_LANG['addonAA']['ipManagement']['filters']['Private'] = 'Private';
$_LANG['addonAA']['ipManagement']['newIP']['private']['label'] = 'Private Address';
$_LANG['addonAA']['ipManagement']['newIP']['private']['options']['on'] = ' Tick to enable private IP addresses';
$_LANG['addonAA']['ipManagement']['editIP']['private']['options']['on'] = 'Tick to edit the private IP address';
$_LANG['addonAA']['ipManagement']['editIP']['private']['label'] = 'Private Address';


$_LANG['addonAA']['servers']['header']['Servers']='Servers List';
$_LANG['addonAA']['servers']['tableHeader']['Name']='Name';
$_LANG['addonAA']['servers']['tableHeader']['IP Address']='IP Address';
$_LANG['addonAA']['servers']['tableHeader']['Active Accounts']='Active Accounts';
$_LANG['addonAA']['servers']['tableHeader']['RAM Assigned / Total / ']='RAM Assigned / Total / ';
$_LANG['addonAA']['servers']['search']='Search';
$_LANG['addonAA']['servers']['tableHeader']['Free']='Free';
$_LANG['addonAA']['servers']['tableHeader']['Suspended']='Suspended';
$_LANG['addonAA']['servers']['tableHeader']['Status']='Status';
$_LANG['addonAA']['servers']['tableHeader']['VM Range']='VM Range';
$_LANG['addonAA']['servers']['tableHeader']['Actions']='Actions';
$_LANG['addonAA']['servers']['noAvailable']='Not Available';
$_LANG['addonAA']['servers']['noAvailableInfo']='';
$_LANG['addonAA']['servers']['previous']='Previous';
$_LANG['addonAA']['servers']['next']='Next';
$_LANG['addonAA']['servers']['actionButtons']['manage']='Manage';
$_LANG['addonAA']['servers']['actionButtons']['edit']='Edit';
$_LANG['addonAA']['servers']['modal']['VM Range']='VM Range: '; 
$_LANG['addonAA']['servers']['modal']['Save Changes']='Save Changes';
$_LANG['addonAA']['servers']['modal']['close']='Close';
$_LANG['subPagesTitles']['servers']['settings']='Default Settings';


$_LANG['addonAA']['servers']['VM Range']='VM Range';
$_LANG['addonAA']['servers']['100']='100';
$_LANG['addonAA']['servers']['150']='150';
$_LANG['addonAA']['servers']['messages']['editSuccess']='The VM range for the server %s has been edited successfully';


$_LANG['subPagesTitles']['servers']['list']='List';
$_LANG['subPagesTitles']['servers']['vmList']='VMs List';
$_LANG['addonAA']['servers']['header']['VM List']='VMs List';
$_LANG['addonAA']['servers']['filters']['toggle']='Toggle Filters';
$_LANG['addonAA']['servers']['filters']['server']='Server'; 
$_LANG['addonAA']['servers']['filters']['Reset']='Reset';
$_LANG['addonAA']['servers']['filters']['Filter']='Filter';
$_LANG['addonAA']['servers']['filters']['server']='Server'; 
$_LANG['addonAA']['servers']['filters']['IP Address']='IP Address';
$_LANG['addonAA']['servers']['filters']['Client']='Client';
$_LANG['addonAA']['servers']['filters']['Domain']='Domain';
$_LANG['addonAA']['servers']['filters']['Status']='Status'; 

$_LANG['addonAA']['servers']['Any']='Any';
$_LANG['addonAA']['servers']['Pending']='Pending';
$_LANG['addonAA']['servers']['Active']='Active';
$_LANG['addonAA']['servers']['Suspended']='Suspended';
$_LANG['addonAA']['servers']['Terminated']='Terminated';
$_LANG['addonAA']['servers']['Cancelled']='Cancelled';
$_LANG['addonAA']['servers']['Fraud']='Fraud';
$_LANG['addonAA']['servers']['tableHeader']['ID']='ID';
$_LANG['addonAA']['servers']['tableHeader']['Product']='Product';
$_LANG['addonAA']['servers']['tableHeader']['Client']='Client';
$_LANG['addonAA']['servers']['tableHeader']['Domain']='Domain';
$_LANG['addonAA']['servers']['tableHeader']['Details']='Details';
$_LANG['addonAA']['servers']['Any']='Any';
$_LANG['addonAA']['servers']['Pending']='Pending';
$_LANG['addonAA']['servers']['Active']='Active';
$_LANG['addonAA']['servers']['Suspended']='Suspended';
$_LANG['addonAA']['servers']['Terminated']='Terminated';
$_LANG['addonAA']['servers']['Cancelled']='Cancelled';
$_LANG['addonAA']['servers']['Fraud']='Fraud';
$_LANG['addonAA']['servers']['tableHeader']['ID']='ID';
$_LANG['addonAA']['servers']['tableHeader']['Product']='Product';
$_LANG['addonAA']['servers']['tableHeader']['Client']='Client';
$_LANG['addonAA']['servers']['tableHeader']['Domain']='Domain';
$_LANG['addonAA']['servers']['tableHeader']['Details']='Details';
$_LANG['addonAA']['servers']['Any']='Any';
$_LANG['addonAA']['servers']['Pending']='Pending';
$_LANG['addonAA']['servers']['Active']='Active';
$_LANG['addonAA']['servers']['Suspended']='Suspended';
$_LANG['addonAA']['servers']['Terminated']='Terminated';
$_LANG['addonAA']['servers']['Cancelled']='Cancelled';
$_LANG['addonAA']['servers']['Fraud']='Fraud';
$_LANG['addonAA']['servers']['tableHeader']['ID']='ID';
$_LANG['addonAA']['servers']['tableHeader']['Product']='Product';
$_LANG['addonAA']['servers']['tableHeader']['Client']='Client';
$_LANG['addonAA']['servers']['tableHeader']['Domain']='Domain';
$_LANG['addonAA']['servers']['tableHeader']['Details']='Details';
$_LANG['addonAA']['servers']['Any']='Any';
$_LANG['addonAA']['servers']['Pending']='Pending';
$_LANG['addonAA']['servers']['Active']='Active';
$_LANG['addonAA']['servers']['Suspended']='Suspended';
$_LANG['addonAA']['servers']['Terminated']='Terminated';
$_LANG['addonAA']['servers']['Cancelled']='Cancelled';
$_LANG['addonAA']['servers']['Fraud']='Fraud';
$_LANG['addonAA']['servers']['tableHeader']['ID']='ID';
$_LANG['addonAA']['servers']['tableHeader']['Product']='Product';
$_LANG['addonAA']['servers']['tableHeader']['Client']='Client';
$_LANG['addonAA']['servers']['tableHeader']['Domain']='Domain';
$_LANG['addonAA']['servers']['tableHeader']['Details']='Details';
$_LANG['addonAA']['servers']['filters']['Node']='Node';
$_LANG['addonAA']['servers']['filters']['VMID']='VMID';
$_LANG['addonAA']['servers']['Server']='Server: ';
$_LANG['addonAA']['servers']['Node']='Node: ';
$_LANG['addonAA']['servers']['VMID']='VMID: '; 
$_LANG['addonAA']['servers']['tableHeader']['Product / Service']='Product / Service';
$_LANG['addonAA']['servers']['tableHeader']['Server']='Server';
$_LANG['addonAA']['servers']['filters']['Type']='Type';
$_LANG['addonAA']['servers']['proxmoxVPS']='VPS';
$_LANG['addonAA']['servers']['proxmoxCloud']='Cloud';
$_LANG['addonAA']['servers']['tableHeader']['VM']='VM';
$_LANG['addonAA']['servers']['actionButtons']['Details']='Show Details';
$_LANG['addonAA']['servers']['modal']['VM Details']='Product / Service: ';
$_LANG['addonAA']['servers']['modal']['Node']='Node';
$_LANG['addonAA']['servers']['modal']['VMID']='VMID';

$_LANG['addonAA']['servers']['modal']['Virutal Server No Available.']='The virtual server is not available';
$_LANG['addonAA']['templates']['actionButtons']['delete'] = 'Delete';

$_LANG['addonAA']['pagesLabels']['settings']['label'] = 'Settings';
$_LANG['addonAA']['pagesLabels']['settings']['vmCleaner'] = 'VM Cleaner';
$_LANG['addonAA']['pagesLabels']['settings']['settings'] = 'General Settings';

$_LANG['addonAA']['settings']['header']['settings']='General Settings';
$_LANG['addonAA']['settings']['configuration']['minimumRangeID']['label']='Minimum VMID';
$_LANG['addonAA']['settings']['button']['Save Changes']='Save Changes';
$_LANG['addonAA']['settings']['messages']['settingSaved']='Default settings have been saved successfully';
$_LANG['addonAA']['settings']['header']['cron']='Cron';
$_LANG['addonAA']['settings']['CronProxmoxVPS']='The cron job for Proxmox VPS (each 5 minutes suggested)';
$_LANG['addonAA']['settings']['CronProxmoxCloud']='The cron job for Proxmox Cloud (each 5 minutes suggested)';
$_LANG['addonAA']['settings']['CronSync']='The cron job for users synchronization (run only once): ';

$_LANG['addonAA']['settings']['header']['VM Cleaner'] = 'VM Cleaner';
$_LANG['addonAA']['settings']['description'] = 'VM Cleaner allows you to track virtual machines existing only on your Proxmox server that are not visible in your WHMCS. Consequently, you are allowed here to sort and delete only those VMs that are not manageable from your WHMCS.';

$_LANG['addonAA']['ipManagement']['editIP']['cidr']['label'] = 'CIDR';
$_LANG['addonAA']['ipManagement']['tableHeader']['CIDR'] = 'CIDR';

$_LANG['addonAA']['pagesLabels']['servers']['recoveryVmList'] = 'Recovery VM List';
$_LANG['addonAA']['servers']['header']['Recovery VM List'] = 'Recovery VM List';
$_LANG['addonAA']['servers']['tableHeader']['Client Name'] = 'Client Name';
$_LANG['addonAA']['servers']['tableHeader']['Node'] = 'Node';
$_LANG['addonAA']['servers']['tableHeader']['VMID'] = 'VMID';
$_LANG['addonAA']['servers']['tableHeader']['VM Details'] = 'VM Details';
$_LANG['addonAA']['servers']['Export To File'] = 'Export To File';
$_LANG['addonAA']['servers']['tableHeader']['Last Update'] = 'Last Update';
$_LANG['addonAA']['settings']['CronRecovery'] = 'The cron job for VM recovery synchronization: ';
$_LANG['addonAA']['settings']['CronMigrate'] = 'The cron job for VMs migration synchronization: ';
$_LANG['addonAA']['servers']['qemu'] = 'KVM';
$_LANG['addonAA']['servers']['lxc'] = 'LXC';
$_LANG['addonAA']['servers']['tableHeader']['Virtualization'] = 'Virtualization';
$_LANG['addonAA']['servers']['tableHeader']['Config'] = 'Config';
$_LANG['addonAA']['servers']['tableHeader']['DNS'] = 'DNS';
$_LANG['addonAA']['servers']['modal']['Recovery Details'] = 'Recovery Details';
$_LANG['addonAA']['servers']['modal']['Config'] = 'Config';
$_LANG['addonAA']['servers']['modal']['Status'] = 'Status';
$_LANG['addonAA']['servers']['modal']['DNS'] = 'DNS';
$_LANG['addonAA']['servers']['filters']['Virtualization'] = 'Virtualization';
$_LANG['addonAA']['servers']['openvz'] = 'OpenVZ';
$_LANG['addonAA']['servers']['The value should be a number'] = 'Please provide a numeric value';
$_LANG['addonAA']['ipManagement']['Invalid Mask: %s'] = 'Invalid Mask: %s';
$_LANG['addonAA']['ipManagement']['Mask is required'] = 'The mask is required';
$_LANG['addonAA']['ipManagement']['tableHeader']['Public'] = 'Public';
$_LANG['addonAA']['servers']['Loading...'] = 'Loading...';
$_LANG['addonAA']['ipManagement']['newIP']['tag']['label'] = 'Tag';
$_LANG['addonAA']['ipManagement']['tableHeader']['VLAN'] = 'VLAN';
$_LANG['addonAA']['ipManagement']['tableHeader']['Tag'] = 'Tag';
$_LANG['addonAA']['ipManagement']['editIP']['tag']['label'] = 'Tag';
$_LANG['addonAA']['servers']['Task History'] = 'Task History';
$_LANG['addonAA']['servers']['ID'] = 'ID';
$_LANG['addonAA']['servers']['Product / Service'] = 'Product / Service';
$_LANG['addonAA']['servers']['Status'] = 'Status';
$_LANG['addonAA']['servers']['Name'] = 'Name';
$_LANG['addonAA']['servers']['Description'] = 'Description';
$_LANG['addonAA']['servers']['Start Time'] = 'Start Time';
$_LANG['addonAA']['servers']['End Time'] = 'End Time';
$_LANG['addonAA']['servers']['Delete Tasks'] = 'Delete Tasks';
$_LANG['addonAA']['servers']['modal']['Delete Tasks '] = 'Delete Tasks ';
$_LANG['addonAA']['servers']['modal']['delete'] = 'Delete';
$_LANG['addonAA']['pagesLabels']['servers']['task'] = 'Task';
$_LANG['addonAA']['servers']['status']['0'] = 'Pending';
$_LANG['addonAA']['servers']['status']['1'] = 'Finished';
$_LANG['addonAA']['servers']['status']['2'] = 'Error';
$_LANG['addonAA']['settings']['Cron job tasks synchronization: '] = 'Cron job tasks synchronization: ';
$_LANG['addonAA']['servers']['Tasks have been deleted'] = 'Tasks have been deleted successfully';
$_LANG['addonAA']['servers']['th']['VMID'] = 'VMID ';
$_LANG['addonAA']['servers']['th']['Node'] = 'Node';

$_LANG['addonAA']['servers']['DHCP'] = 'DHCP';
$_LANG['addonAA']['servers']['Hostname'] = 'Hostname';
$_LANG['addonAA']['servers']['IP Address'] = 'IP';
$_LANG['addonAA']['servers']['Configuration For IPv4'] = 'Configuration For IPv4';
$_LANG['addonAA']['servers']['Configuration For IPv6'] = 'Configuration For IPv6';
$_LANG['addonAA']['servers']['Actions'] = 'Actions';
$_LANG['addonAA']['pagesLabels']['servers']['dhcp'] = 'DHCP';
$_LANG['addonAA']['servers']['Edit'] = 'Edit';
$_LANG['addonAA']['servers']['Successful!'] = 'Success!';
$_LANG['addonAA']['servers']['Add'] = 'Add';
$_LANG['addonAA']['servers']['New DHCP Server'] = 'New DHCP Server';
$_LANG['addonAA']['servers']['Hostname is invalid'] = 'The hostname is invalid';
$_LANG['addonAA']['servers']['That IP Address is invalid'] = 'The IP address is invalid';
$_LANG['addonAA']['servers']['Port'] = 'Port';
$_LANG['addonAA']['servers']['Port is invalid'] = 'The port is invalid';
$_LANG['addonAA']['servers']['Username'] = 'Username';
$_LANG['addonAA']['servers']['Username is reguired'] = 'The username is required';
$_LANG['addonAA']['servers']['Password'] = 'Password';
$_LANG['addonAA']['servers']['Password is reguired'] = 'The password is required';
$_LANG['addonAA']['servers']['Path For IPv4'] = 'Path For IPv4';
$_LANG['addonAA']['servers']['Path is invalid'] = 'The path is invalid';
$_LANG['addonAA']['servers']['Path For IPv6'] = 'Path For IPv6';
$_LANG['addonAA']['servers']['Test Connection'] = 'Test Connection';
$_LANG['addonAA']['servers']['Delete server:'] = 'Delete server:';
$_LANG['addonAA']['servers'][' Are you sure you want to delete that server?'] = ' Are you sure that you want to delete this server?';
$_LANG['addonAA']['servers']['Delete'] = 'Delete';
$_LANG['addonAA']['servers']['Close'] = 'Close';
$_LANG['addonAA']['servers']['DHCP Server \'%s\' has been deleted.'] = 'The DHCP server \'%s\' has been deleted successfully';
$_LANG['addonAA']['servers']['DHCP Server \'%s\' has been added.'] = 'The DHCP server \'%s\' has been added successfully';
$_LANG['addonAA']['servers']['DHCP Server \'%s\' has been saved.'] = 'The DHCP server \'%s\' has been saved successfully';
$_LANG['addonAA']['servers']['Public Key File'] = 'Public Key File';
$_LANG['addonAA']['servers']['Public Key File is invalid'] = 'The public key file is invalid';
$_LANG['addonAA']['servers']['Private Key File'] = 'Private Key File';
$_LANG['addonAA']['servers']['Private Key File is invalid'] = 'The private key file is invalid';
$_LANG['addonAA']['ipManagement']['editIP']['node']['label']='Node';
$_LANG['addonAA']['ipManagement']['editIP']['node']['description']='';
$_LANG['addonAA']['ipManagement']['newIP']['node']['label'] = 'Node';
$_LANG['addonAA']['ipManagement']['newIP']['node']['description'] = '';
$_LANG['addonAA']['ipManagement']['tableHeader']['Node'] = 'Node';
$_LANG['addonAA']['ipManagement']['Tag  must have a maximum value of 4094.'] = 'The tag may have a maximum value of 4094.';
$_LANG['addonAA']['ipManagement']['Mask must have range between 8-120'] = 'The mask should be within the range between 8-120';
$_LANG['addonAA']['servers']['Edit DHCP Server'] = 'Edit DHCP Server';
$_LANG['addonAA']['templates']['Description'] = 'Description';
$_LANG['addonAA']['pagesLabels']['settings']['sshKeys'] = 'SSH Keys';
$_LANG['addonAA']['settings']['SSH Keys'] = 'SSH Keys';
$_LANG['addonAA']['settings']['Id'] = 'ID';
$_LANG['addonAA']['settings']['Name'] = 'Name';
$_LANG['addonAA']['settings']['Public Key'] = 'Public Key';
$_LANG['addonAA']['settings']['Private Key'] = 'Private Key';
$_LANG['addonAA']['settings']['Actions'] = 'Actions';
$_LANG['addonAA']['settings']['Add'] = 'Add';
$_LANG['addonAA']['settings']['New SSH Key'] = 'New SSH Key';
$_LANG['addonAA']['settings']['Public'] = 'Public';
$_LANG['addonAA']['settings']['Private'] = 'Private';
$_LANG['addonAA']['settings']['modal']['Save Changes'] = 'Save Changes';
$_LANG['addonAA']['settings'][' Public key file \'%s\' does not exist'] = ' The public key file \'%s\' does not exist';
$_LANG['addonAA']['settings'][' Private key file \'%s\' does not exist'] = ' The private key file \'%s\' does not exist';
$_LANG['addonAA']['settings']['Public key file  is empty'] = 'The public key file is empty';
$_LANG['addonAA']['settings']['Private key file  is empty'] = 'The private key file is empty';
$_LANG['Delete'] = 'Delete';
$_LANG['Edit'] = 'Edit';
$_LANG['addonAA']['settings']['Edit SSH Key'] = 'Edit SSH Key';
$_LANG['addonAA']['settings']['SSH Key:'] = 'SSH Key:';
$_LANG['addonAA']['settings'][' Are you sure you want to delete that SSH Key?'] = ' Are you sure that you want to delete this SSH key?';
$_LANG['Close'] = 'Close';
$_LANG['addonAA']['settings']['SSH Key \'%s\' has been saved.'] = 'The SSH key \'%s\' has been saved successfully';
$_LANG['addonAA']['settings']['SSH Key \'%s\' has been deleted.'] = 'The SSH key \'%s\' has been deleted successfully';
$_LANG['addonAA']['settings']['SSH Key \'%s\' has been added.'] = 'The SSH key \'%s\' has been added successfully';
$_LANG['addonAA']['ipManagement']['tableHeader']['VLAN Trunks'] = 'VLAN Trunks';
$_LANG['addonAA']['servers']['Id'] = 'ID';
$_LANG['addonAA']['settings']['Passphrase'] = 'Passphrase';
$_LANG['CPU Usage'] = 'CPU Usage';
$_LANG['IO Delay'] = 'IO Delay';
$_LANG['Server Load'] = 'Server Load';
$_LANG['Memory Usage'] = 'Memory Usage';
$_LANG['Total'] = 'Total';
$_LANG['Net In'] = 'Net In';
$_LANG['Net Out'] = 'Net Out';
$_LANG['addonAA']['servers']['Delete Selected'] = 'Delete';
$_LANG['addonAA']['servers']['Delete With Status'] = 'Delete With Status';
$_LANG['addonAA']['servers']['Are you sure you want to delete the selected tasks?'] = 'Are you sure that you want to delete the selected tasks?';
$_LANG['addonAA']['settings']['Modules'] = 'Modules';
$_LANG['proxmoxVPS'] = 'ProxmoxVPS';
$_LANG['proxmoxCloud'] = 'ProxmoxCloud';
$_LANG['addonAA']['settings']['modules-help'] = '';
$_LANG['addonAA']['settings']['Reading file content "%s" failed, please check file permission'] = 'Reading of the file content "%s" has failed, please check the file permissions';<?php

$_LANG['general']['back'] = 'Back To Service';
$_LANG['general']['graph_of'] = 'of';
$_LANG['general']['graph_used'] = 'Used';
$_LANG['general']['graph_free'] = 'Free';
$_LANG['general']['console_info'] = 'The console requires Java software. You need to accept the \'security risk\' popup in order to run it.';
$_LANG['general']['btn_enable'] = 'Enable';
$_LANG['general']['btn_disable'] = 'Disable';
$_LANG['general']['connection_error'] = 'Connection error';
$_LANG['general']['unlimited'] = 'Unlimited';
$_LANG['general']['add'] = 'Add';
$_LANG['general']['cancel'] = 'Cancel';
$_LANG['general']['total'] = 'Total';
$_LANG['general']['usage'] = 'Usage';
$_LANG['general']['save'] = 'Save Changes';
$_LANG['general']['update'] = 'Update';
$_LANG['general']['delete'] = 'Delete';
$_LANG['general']['confirm'] = 'Are you sure that you want to proceed?';
$_LANG['general']['none'] = 'None';
$_LANG['main_header'] = 'Manage Your Server';
$_LANG['additionals'] = 'Additional Tools';
$_LANG['vm_details'] = 'VM Details';
$_LANG['actions'] = 'Actions';
$_LANG['Edit'] = 'Edit';
$_LANG['cloud']['edit_server'] = 'Edit Server Details';
$_LANG['cloud']['edit_vm'] = 'Edit VM';
$_LANG['cloud']['add_new_server'] = 'Add New Server';
$_LANG['cloud_ajax']['no_server'] = 'You need to setup the server first';
$_LANG['cloud_ajax']['no_access'] = 'You have no access to this action';
$_LANG['cloud']['status'] = 'Status';
$_LANG['cloud']['type'] = 'Type';
$_LANG['cloud']['template'] = 'Template';
$_LANG['cloud']['iso'] = 'CD-ROM: ISO';
$_LANG['cloud']['hostname'] = 'Hostname';
$_LANG['cloud']['bandwidth'] = 'Bandwidth';
$_LANG['cloud']['main_ip'] = 'Main IP Address';
$_LANG['cloud']['ip_addresses'] = 'IP Addresses';
$_LANG['cloud']['root_password'] = 'Root Password';
$_LANG['cloud']['root_pass_show'] = 'Show';
$_LANG['cloud']['root_change_password'] = 'Change Password';
$_LANG['cloud']['root_pass_change'] = 'Change';
$_LANG['cloud']['rebuild'] = 'Rebuild';
$_LANG['cloud']['shutdown'] = 'Shutdown';
$_LANG['cloud']['reboot'] = 'Reboot';
$_LANG['cloud']['console'] = 'Console';
$_LANG['cloud']['control_panel'] = 'Control Panel';
$_LANG['cloud']['boot'] = 'Boot';
$_LANG['cloud']['change_iso'] = 'Change';
$_LANG['cloud']['change'] = 'Change';
$_LANG['cloud']['change_hostname'] = 'Change Hostname';
$_LANG['cloud']['details'] = 'Details';
$_LANG['cloud']['graphs'] = 'Usage Graphs';
$_LANG['cloud']['graph_cpu'] = 'CPU Usage %';
$_LANG['cloud']['graph_mem'] = 'Memory Usage';
$_LANG['cloud']['graph_net'] = 'Network Traffic';
$_LANG['cloud']['graph_disk'] = 'Disk IO';
$_LANG['cloud']['graph_no_cpu'] = 'The traffic graph is not available yet';
$_LANG['cloud']['graph_no_mem'] = 'The memory graph is not available yet';
$_LANG['cloud']['graph_no_net'] = 'The network graph is not available yet';
$_LANG['cloud']['graph_generated'] = 'Graphs have been generated successfully';
$_LANG['cloud']['graph_no_disk'] = 'The disk graph is not available yet';
$_LANG['cloud']['graph_traffic'] = 'Traffic';
$_LANG['cloud']['graph_load_average'] = 'Load Average';
$_LANG['cloud']['graph_memory'] = 'Memory';
$_LANG['cloud']['boot_order'] = 'Boot Order';
$_LANG['cloud']['btn_boot_order'] = 'Change';
$_LANG['cloud']['new_server_details'] = 'New Server Details';
$_LANG['cloud']['upgrade_server'] = 'Upgrade Your Server';
$_LANG['cloud']['ram'] = 'RAM';
$_LANG['cloud']['cpu_cores'] = 'CPU Cores';
$_LANG['cloud']['swap'] = 'SWAP';
$_LANG['cloud']['sockets'] = 'CPU Sockets';
$_LANG['cloud']['cpu_weight'] = 'CPU Weight';
$_LANG['cloud']['backup_size'] = 'Backup Size';
$_LANG['cloud']['backup_files'] = 'Backup Files';
$_LANG['cloud']['disk_space'] = 'Disk Space';
$_LANG['cloud']['control_panel'] = 'Control Panel';
$_LANG['cloud']['cpanel_monthly'] = 'cPanel monthly';
$_LANG['cloud']['cpanel_yearly'] = 'cPanel yearly';
$_LANG['cloud']['btn_add'] = 'Add New Virtual Server';
$_LANG['cloud']['btn_upgrade'] = 'Upgrade';
$_LANG['cloud']['upgrade_info'] = 'Upgrade is not automated. An email will be sent to the administrator and they need to upgrade the virtual server manually.';
$_LANG['cloud']['create_virtual_server'] = 'New Server Details';
$_LANG['cloud']['manage'] = 'Manage';
$_LANG['cloud']['no_virtual_servers'] = 'No virtual servers yet';
$_LANG['cloud']['no_access_to_vserver'] = 'You have no access to this server';
$_LANG['cloud']['rebuild_template'] = 'Select Template:';
$_LANG['cloud']['rebuild_no_templates'] = 'No templates available';
$_LANG['cloud']['console_pass'] = 'Password:';
$_LANG['cloud']['console_session'] = 'Session Expired:';
$_LANG['cloud_ajax']['unknown'] = 'Unknown error';
$_LANG['cloud']['your_resources'] = 'Your Resources';
$_LANG['cloud']['your_virtual_servers'] = 'Your Virtual Servers';
$_LANG['cloud']['virtual_servers'] = 'Virtual Servers';
$_LANG['cloud']['please_wait'] = 'Please wait...';
$_LANG['cloud']['ns1'] = 'Nameserver 1';
$_LANG['cloud']['ns2'] = 'Nameserver 2';
$_LANG['cloud']['delete'] = 'Delete';
$_LANG['cloud']['rebuild'] = 'Reinstall';
$_LANG['cloud']['shutdown'] = 'Shutdown';
$_LANG['cloud']['reinstall'] = 'Reinstall';
$_LANG['cloud']['stop'] = 'Stop';
$_LANG['cloud']['reboot'] = 'Reboot';
$_LANG['cloud']['console'] = 'VNC Console';
$_LANG['cloud']['backup'] = 'Backups';
$_LANG['cloud']['create_backup'] = 'Backups';
$_LANG['cloud']['schedule_backup'] = 'Backup Jobs';
$_LANG['cloud']['cpu_units'] = 'CPU Units';
$_LANG['cloud']['uptime'] = 'Uptime';
$_LANG['cloud']['cpu_usage'] = 'CPU Usage';
$_LANG['cloud']['memory'] = 'Memory';
$_LANG['cloud']['disk'] = 'Disk';
$_LANG['cloud']['ip_addresses'] = 'IP Addresses';
$_LANG['cloud']['ip_address'] = 'IP Address';
$_LANG['cloud']['mac_address'] = 'MAC Address';
$_LANG['cloud']['subnet_mask'] = 'Subnet Mask';
$_LANG['cloud']['gateway'] = 'Gateway';
$_LANG['cloud']['dns'] = 'DNS Domain';
$_LANG['cloud']['dns_server'] = 'DNS Server';
$_LANG['cloud']['backups_files_limit'] = 'Backups Files Limit';
$_LANG['cloud']['network_rate'] = 'Network Rate';
$_LANG['cloud']['hour'] = "Hour";
$_LANG['cloud']['day'] = "Day";
$_LANG['cloud']['week'] = "Week";
$_LANG['cloud']['month'] = "Month";
$_LANG['cloud']['year'] = "Year";
$_LANG['cloud']['backup_jobs'] = 'Backup Jobs';
$_LANG['cloud']['no_backup_files'] = 'Empty';
$_LANG['cloud']['backup_id'] = 'ID';
$_LANG['cloud']['backup_start_time'] = 'Start Time';
$_LANG['cloud']['backup_day_of_week'] = 'Day of Week';
$_LANG['cloud']['backup_compress'] = 'Compression Type';
$_LANG['cloud']['backup_mode'] = 'Backup Mode';
$_LANG['cloud']['backup_new'] = 'New Backup';
$_LANG['cloud']['new_schedule'] = 'New Job';
$_LANG['cloud']['no_backup_job'] = 'Empty';
$_LANG['cloud']['backup_file'] = 'File';
$_LANG['cloud']['backup_format'] = 'Format';
$_LANG['cloud']['backup_actions'] = 'Actions';
$_LANG['cloud']['backup_error_size'] = 'The maximum size set for a backup has been exceeded. Please remove the old backup files.';
$_LANG['cloud']['backup_error_maxfiles'] = 'The maximum number of backup files has been exceeded. Please remove the old backup files.';
$_LANG['cloud']['backup_error_maxjobs'] = 'The maximum number of backup jobs has been exceeded. Please remove the old backup jobs.';
$_LANG['cloud']['new_backup'] = 'New Backup';
$_LANG['cloud']['backup_restore_info'] = 'Are you sure that you want to restore this virtual machine? This action will permanently erase the current VM data.';
$_LANG['cloud']['backup_reload'] = 'The backup list has been reloaded successfully';
$_LANG['cloud']['backup_remove'] = 'Remove Old Backup Files';
$_LANG['cloud']['restore'] = 'Restore';
$_LANG['cloud']['boot_order_1'] = 'Device 1:';
$_LANG['cloud']['boot_order_2'] = 'Device 2:';
$_LANG['cloud']['boot_order_3'] = 'Device 3:';
$_LANG['cloud']['week_array'] = array("mon" => "Monday", "tue" => "Tuesday", "wed" => "Wednesday", "thu" => "Thursday", "fri" => "Friday", "sat" => "Saturday", "sun" => "Sunday");
$_LANG['cloud_ajax']['server_deleted'] = 'The server has been deleted successfully';
$_LANG['cloud_ajax']['boot'] = 'The container has been booted successfully';
$_LANG['cloud_ajax']['reboot'] = 'The container has been rebooted successfully';
$_LANG['cloud_ajax']['stop'] = 'The container has been stopped successfully';
$_LANG['cloud_ajax']['shutdown'] = 'The container has been shut down successfully';
$_LANG['cloud_ajax']['created_schedule'] = 'The backup job has been created successfully';
$_LANG['cloud_ajax']['deleted_schedule'] = 'The backup job has been deleted successfully';
$_LANG['cloud_ajax']['updated_schedule'] = 'The backup job has been updated successfully';
$_LANG['cloud_ajax']['backup_now'] = 'The backup creation is in progress';
$_LANG['cloud_ajax']['backup_deleted'] = 'The backup has been deleted successfully';
$_LANG['cloud_ajax']['backup_restore'] = 'The virtual machine has been restored successfully';
$_LANG['cloud_ajax']['iso_changed'] = 'The ISO image has been changed successfully';
$_LANG['cloud_ajax']['boot_changed'] = 'The boot order has been changed successfully';
$_LANG['cloud_ajax']['no_vm'] = 'Please select VM';
$_LANG['cloud_ajax']['unknown'] = "Unknown error";



//Proxmox Cloud version 1.1.0
$_LANG['cloud']['ipv4_addresses'] = 'IPv4';
$_LANG['cloud']['ipv6_addresses'] = 'IPv6';
$_LANG['cloud']['task_history'] = 'Task History';
$_LANG['cloud']['node'] = 'Node';
$_LANG['cloud']['task_history'] = 'Task History';
$_LANG['cloud']['start_time'] = 'Start Time';
$_LANG['cloud']['end_time'] = 'End Time';
$_LANG['cloud']['description'] = 'Description';
$_LANG['cloud']['nothing_to_display'] = 'Nothing to display';
$_LANG['cloud']['vlan_tag'] = 'VLAN Tag';
$_LANG['cloud']['msg_backup_routing'] = 'Your routing backup limit is %d. When you exceed this limit, the last backup will be replaced with a new one.';
$_LANG['cloud']['kvm_os_template'] = 'KVM OS Template';

$_LANG['logs']['main_header'] = 'Scheduled Task';
$_LANG['logs']['button'] = 'Scheduled Task';
$_LANG['logs']['task'] = 'Task';
$_LANG['logs']['created'] = 'Created';
$_LANG['logs']['last_update'] = 'Last Update';
$_LANG['logs']['attempts'] = 'Attempts';
$_LANG['logs']['message'] = 'Message';
$_LANG['logs']['status'] = 'Status';
$_LANG['logs']['msg_in_progress'] = 'The task is in progress';
$_LANG['logs']['msg_for_processing'] = 'Waiting for task processing';
$_LANG['logs']['msg_task_stuck'] = "The task is stuck from: ";
$_LANG['logs']['msg_not_processed'] = "The task is not processed yet";
$_LANG['logs']['msg_no_tasks'] = "You do not have any scheduled tasks";
$_LANG['cloud']['do_change_iso'] = "Are you sure that you want to change CD-ROM ISO?";
$_LANG['cloud']['vm_delete'] = 'Are you sure that you want to delete this virtual server?';
$_LANG['cloud']['backup_delete'] = 'Are you sure that you want to delete this backup?';

//new @version 1.4.0

$_LANG['button_spice'] = "SPICE Console";
$_LANG['cloud']['status'] = 'Status';
$_LANG['cloud']['management'] = 'Management';
$_LANG['cloud']['network'] = 'Network';
$_LANG['cloud']['cpu_cores_ifo'] = '(per socket)';


$_LANG['network']['header'] = 'Network';
$_LANG['network']['type'] = 'Type';
$_LANG['network']['name'] = 'IP Address / Name';
$_LANG['network']['bridge'] = 'Bridge';
$_LANG['network']['mac'] = 'MAC Address';
$_LANG['network']['empty'] = 'No networks available';

$_LANG['network']['type_ip'] = 'IP Address';
$_LANG['network']['type_device'] = 'Network Device';

$_LANG['network']['new'] = 'New Private Network';
$_LANG['network']['added'] = 'The private network has been added successfully';
$_LANG['network']['action'] = 'Action';

$_LANG['network']['delete'] = 'Are you sure that you want to delete this network?';
$_LANG['network']['deleted'] = 'The private network has been deleted successfully';
$_LANG['network']['tag'] = 'Tag';
$_LANG['CAPages']['network']['ID'] = 'ID';
$_LANG['CAPages']['network']['name'] = 'Name';
$_LANG['CAPages']['network']['bridge'] = 'Bridge';
$_LANG['CAPages']['network']['firewall'] = 'Firewall';
$_LANG['CAPages']['network']['VLAN Tag'] = 'VLAN Tag';
$_LANG['CAPages']['network']['MAC Address'] = 'MAC Address';
$_LANG['CAPages']['network']['IP Address'] = 'IP Address';
$_LANG['CAPages']['network']['Gateway'] = 'Gateway';

$_LANG['cloud']['snapshots'] = 'Snapshots';
$_LANG['snapshots']['header'] = 'Snapshots';
$_LANG['snapshots']['name'] = 'Name';
$_LANG['snapshots']['ram'] = 'RAM';
$_LANG['snapshots']['date_status'] = 'Date';
$_LANG['snapshots']['status'] = 'Status';
$_LANG['snapshots']['description'] = 'Description';
$_LANG['snapshots']['action'] = 'Actions';
$_LANG['snapshots']['empty'] = 'No snapshots available';
$_LANG['snapshots']['err_alphabetical'] = 'Only alphabetical characters are allowed';
$_LANG['snapshots']['deleteMsg'] = 'Are you sure that you want to delete this snapshot?';
$_LANG['snapshots']['ram_on'] = 'Yes';
$_LANG['snapshots']['ram_off'] = 'No';
$_LANG['snapshots']['activated'] = 'Activated';
$_LANG['snapshots']['deleted'] = 'The snapshot has been deleted successfully';
$_LANG['snapshots']['updated'] = 'The snapshot has been updated successfully';
$_LANG['snapshots']['delete'] = 'Are you sure that you want to delete this snapshot?';
$_LANG['snapshots']['take_snapshot'] = 'Take Snapshot';
$_LANG['snapshots']['rollback'] = ' Rollback';
$_LANG['snapshots']['rollback_alert'] = 'Are you sure that you want to roll back this snapshot?';
$_LANG['snapshots']['rollbacked'] = 'The snapshot has been rolled back successfully';
$_LANG['snapshots']['close'] = 'Close';
$_LANG['snapshots_form']['name'] = 'Name:';
$_LANG['snapshots_form']['incram'] = 'Include RAM: ';
$_LANG['snapshots_form']['description'] = 'Description: ';
$_LANG['snapshots']['created'] = 'The snapshot has been created successfully';
$_LANG['snapshots']['update'] = 'Update:';
$_LANG['snapshots']['updated'] = 'The snapshot has been updated successfully';


$_LANG['limit']['er_mem'] = 'Unable to allocate %d MB of memory. Memory available: %s. Please contact your administrator.';
$_LANG['limit']['er_disk'] = 'Unable to allocate %d GB of disk space. Disk space available: %s. Please contact your administrator';
$_LANG['limit']['er_swap'] = 'Unable to allocate %d MB of SWAP. SWAP available: %s. Please contact your administrator.';

$_LANG['addserver']['kvm_ostype'] = 'OS Type';
$_LANG['addvm']['description'] = 'Create a new VPS within product limits using a VPS template or ISO image.';
$_LANG['upgrade']['vm_upgrade_success'] = 'The server has been updated successfully';
$_LANG['vserver']['console_novnc'] = 'noVNC';

$_LANG['button_firewall'] = 'Firewall';
$_LANG['firewall']['header'] = 'Firewall';
$_LANG['firewall']['enable'] = 'Enable';
$_LANG['firewall']['type'] = 'Type';
$_LANG['firewall']['action'] = 'Action';
$_LANG['firewall']['source'] = 'Source';

$_LANG['firewall']['macro'] = 'Macro';
$_LANG['firewall']['interface'] = 'Interface';
$_LANG['firewall']['destination'] = 'Destination';
$_LANG['firewall']['protocol'] = 'Protocol';
$_LANG['firewall']['dest_port'] = 'Dest. Port';
$_LANG['firewall']['source_port'] = 'Source Port';
$_LANG['firewall']['comment'] = 'Comment';
$_LANG['firewall']['actions'] = 'Actions';
$_LANG['firewall']['empty'] = 'No rules available';

$_LANG['firewall']['add'] = 'Add';
$_LANG['firewall']['add_rule'] = 'Add Rule';
$_LANG['firewall']['edit_rule'] = 'Edit Rule';
$_LANG['firewall']['close'] = 'Close';

$_LANG['firewall']['direction'] = 'Direction';
$_LANG['firewall']['delete'] = 'Are you sure that you want to delete this rule?';
$_LANG['firewall']['directions'] = array(
    "in" => "in",
    "out" => "out"
);
$_LANG['firewall']['action_select'] = array(
    "ACCEPT" => "ACCEPT",
    "DROP" => "DROP",
    "REJECT" => "REJECT",
);

$_LANG['firewall']['protocols'] = array(
    "tcp" => "6  Transmission Control Protocol",
    "udp" => "17 User Datagram Protocol",
    "icmp" => "1 Internet Control Message Protocol",
    "igmp" => "2 Internet Group Management",
    "ggp" => "3 gateway-gateway protocol",
    "ipencap" => "4 IP encapsulated in IP",
    "st" => "5 ST datagram mode",
    "egp" => "8 exterior gateway protocol",
    "igp" => "9 any private interior gateway (Cisco)",
    "pup" => "12 PARC universal packet protocol",
    "hmp" => "20 host monitoring protocol",
    "xns-idp" => "22 Xerox NS IDP",
    "rdp" => "27 \"reliable datagram\" protocol",
    "iso-tp4" => "29 ISO Transport Protocol class 4 [RFC905]",
    "dccp" => "33 Datagram Congestion Control Prot. ",
    "xtp" => "33 Xpress Transfer Protocol",
    "ddp" => "37 Datagram Delivery Protocol",
    "idpr-cmtp" => "38 IDPR Control Message Transport",
    "ipv6" => "41 Internet Protocol, version 6",
    "ipv6-route" => "43 Routing Header for IPv6",
    "ipv6-frag" => "44 Fragment Header for IPv6",
    "idrp" => "45 Inter-Domain outing Protocol",
    "rsvp" => "46 Reservation Protocol",
    "gre" => "47 General Routing Encapsulation",
    "esp" => "50 Encap Security Payload [RFC2406]",
    "ah" => "51 Authentication Header [RFC2402]",
    "skip" => "57 SKIP",
    "ipv6-icmp" => "58 ICMP for IPv6",
    "ipv6v-nonxt" => "59 No Next Header for IPv6",
    "ipv6-opts" => "60 Destination Options for IPv6",
    "vmtp" => "81 Versatile Message Transport",
    "eigrp" => "88 Enhanced Interior Routing Protocol (Cisco)",
    "ospf" => "89 Open Shortest Path First IGP",
    "ax.25" => "93 AX.25 frames",
    "ipip" => "94 Ip-within-IP Encapsulation Protocol",
    "etherip" => "97 IP-within-IP Encapsulation [RFC3378]",
    "pim" => "103 Protocol Independent Muulticast",
    "ipvomp" => "108 IP Payload Compression Protocol",
    "vrrp" => "112 Virtual Router Redundancy Protocol",
    "l2tp" => "115 Layer Two Tunneling Protocol [RFC2661]",
    "isis" => "124 IS-IS over IPv4",
    "sctp" => "132 Stream Control Transmission Protocol",
    "fc" => "133 Fibre Channel",
    "mobility-header" => "135 Mobility Support for Ipv6 [RFC3775]",
    "udplite" => "136 UDP-Lite [RFC3828]",
    "mpls-in-ip" => "136 UDP-Lite [RFC3828]",
    "hip" => "139 Host Identity Protocol",
    "shim6" => "139 Shim6 Protocol [RFC5533]",
    "wesp" => "141 Wrapped Encapsulating Security Payload",
    "rohc" => "142 Robust Header Compression",
);
$_LANG['firewall']['rule_created'] = 'The rule has been created successfully';
$_LANG['firewall']['rule_updated'] = 'The rule has been updated successfully';
$_LANG['firewall']['rule_delted'] = 'The rule has been removed successfully';
$_LANG['general']['edit'] = 'Edit';
$_LANG['general']['ok'] = 'Ok';
$_LANG['firewall']['add_group'] = 'Insert Security Group';
$_LANG['firewall']['edit_group'] = 'Edit Security Group';
$_LANG['firewall']['security_group'] = 'Security Group';
$_LANG['firewall']['venet'] = 'venet';

$_LANG['vserver']['ostemplate'] = 'Template';
$_LANG['cloud']['reinstallation'] = 'Reinstallation';
$_LANG['rebuild']['header'] = 'Reinstallation';
$_LANG['rebuild']['template'] = 'Template ';
$_LANG['rebuild']['button'] = 'Reinstall';
$_LANG['rebuild']['empty'] = 'No templates available';
$_LANG['rebuild']['err1'] = 'You need to select the template before the reinstallation';
$_LANG['rebuild']['err2'] = 'You have not entered the root password';
$_LANG['rebuild']['password'] = 'New Root Password';
$_LANG['rebuild']['success'] = 'The virtual machine has been reinstalled successfully';

$_LANG['cloud']['networkRate'] = 'Network Rate';
$_LANG['cloud']['unlimited'] = 'Unlimited';

$_LANG['button_novnc'] = "noVNC Console";

$_LANG['button_disksManagement'] = "Disks";


$_LANG['disks']['header'] = 'Disks';
$_LANG['disks']['name'] = 'Name';
$_LANG['disks']['bus'] = 'Bus / Device';
$_LANG['disks']['format'] = 'Format';
$_LANG['disks']['backup'] = 'Backup';
$_LANG['disks']['size'] = 'Size';
$_LANG['disks']['disk-1'] = 'Disk 1';
$_LANG['disks']['disk-2'] = 'Disk 2';
$_LANG['disks']['disk-3'] = 'Disk 3';
$_LANG['disks']['disk-4'] = 'Disk 4';
$_LANG['disks']['disk-5'] = 'Disk 5';
$_LANG['disks']['disk-6'] = 'Disk 6';
$_LANG['disks']['disk-7'] = 'Disk 7';
$_LANG['disks']['disk-8'] = 'Disk 8';
$_LANG['disks']['actons'] = 'Actions';
$_LANG['disks']['empty'] = 'No Disks';
$_LANG['disks']['delete'] = 'Are you sure that you want to delete this hard disk?';
$_LANG['disks']['added'] = 'The hard disk has been added successfully';
$_LANG['disks']['deleted'] = 'The hard disk has been deleted successfully';
$_LANG['disks']['edited'] = 'The hard disk has been edited successfully';
$_LANG['disks']['actions'] = 'Actions';
$_LANG['disks']['add'] = 'Add Hard Disk';
$_LANG['disks']['size_gb'] = 'Size (GB)';
$_LANG['general']['close'] = 'Close';
$_LANG['disks']['formats'] = array(
    'raw' => 'Raw disk image (raw)',
    'qcow2' => 'QEMU image format (qcow2)',
    'vmdk' => 'VM image format (vmdk)'
);

$_LANG['disks']['add_new_hhd'] = 'Add Hard Disk';
$_LANG['disks']['errorAddDisk'] = 'You are not able to set %s GB of disk size. Disk size available: %s GB';
$_LANG['disks']['errorEditDisk'] = 'Disk size downgrading is restricted';


$_LANG['disks']['edit_hhd'] = 'Edit Hard Disk';
$_LANG['disks']['description'] = 'View and manage the hard disk within defined limits. Any additional disks can be removed at will.';
$_LANG['edit']['description'] = 'Edit feature option allows you to change server details and resources.';
$_LANG['panel']['manageSevers'] = 'Manage Servers';

$_LANG['general']['labelDelete'] = 'Delete: ';



$_LANG['disks']['edit_hhd'] = 'Edit Hard Disk';
$_LANG['home']['AdditionalTools'] = 'Additional Tools';
$_LANG['button.management'] = 'Management';
$_LANG['panel']['manageVM'] = 'Manage VM';
$_LANG['panel']['additionalTools'] = 'Additional Tools';
$_LANG['token'] = ' Token ';
$_LANG['reinstall']['header'] = 'Reinstall';
$_LANG['reinstall']['description'] = 'Select the template for reinstallation. If you proceed, all data located on the virtual machine will be lost.';
$_LANG['reinstall']['noTemplate'] = 'Provide the template for reinstallation';
$_LANG['reinstall']['password'] = 'Password:';
$_LANG['reinstall']['template'] = 'OS Template:';
$_LANG['backup']['empty'] = 'No Backups';
$_LANG['backup']['add_new'] = 'Create Backup';
$_LANG['backup']['delete'] = 'Are you sure that you want to delete this file?';

$_LANG['jobs']['empty'] = 'No Backup Jobs';
$_LANG['jobs']['emailNotification'] = 'Email Notification';
$_LANG['jobs']['add_new'] = 'Add Backup Job';
$_LANG['jobs']['mailto'] = 'Email Notification';
$_LANG['jobs']['mailtoDes'] = 'Enable email notifications';
$_LANG['jobs']['delete'] = 'Are you sure that you want to delete this job?';
$_LANG['jobs']['edit'] = 'Edit Backup Job';
$_LANG['jobs']['compressNone'] = 'None';
$_LANG['jobs']['labelDelete'] = 'Delete Job: ';
$_LANG['jobs']['description'] = "Instead of creating backups manually, set up a job, which will automatically create backups for you. Created backups will be available on the 'Backups' page.";


$_LANG['home']['disc'] = 'CD/DVD Disc Image File';
$_LANG['home']['bootOrder'] = 'Boot Order';
$_LANG['home']['boot']['0'] = 'None';
$_LANG['home']['boot']['d'] = 'CD-ROM';
$_LANG['home']['boot']['n'] = 'Network';
$_LANG['home']['boot']['c'] = 'Disk';
$_LANG['home']['boot_order_1'] = 'Device 1:';
$_LANG['home']['boot_order_2'] = 'Device 2:';
$_LANG['home']['boot_order_3'] = 'Device 3:';

$_LANG['CAPages']['taskHistory']['search'] = 'Search';
$_LANG['CAPages']['taskHistory']['noAvailable'] = 'Not Available';
$_LANG['CAPages']['taskHistory']['noAvailableInfo'] = "";
$_LANG['CAPages']['taskHistory']['previous'] = 'Previous';
$_LANG['CAPages']['taskHistory']['next'] = 'Next';

$_LANG['backup']['labelDelete'] = 'Delete Backup: ';
$_LANG['backup']['labelRestore'] = 'Restore Backup: ';
$_LANG['backup']['description'] = 'Secure your system by creating backups. In case of any failure, you can restore your VPS to one of the previously created backups. ';

$_LANG['graph']['description'] = "Your VPS usage over time can be viewed here. If some graphs are close to their maximum value, consider the VPS upgrade.";
$_LANG['task']['description'] = "Any action set to be executed on the server along with its status is displayed here.";

$_LANG['network']['description'] = 'Brief information about the network interfaces used by VPS.';
$_LANG['firewall']['description'] = 'Define firewall rules or enable the security group for your VPS.';
$_LANG['network']['labelDelete'] = 'Delete Network: ';
$_LANG['snapshots']['labelDelete'] = 'Delete Snapshot: ';
$_LANG['snapshots']['labelRollback'] = 'Rollback: ';
$_LANG['snapshots']['descriptionLong'] = "A snapshot includes the content of the virtual machine memory, virtual machine settings, and the state of all the virtual disks. When you roll back to a snapshot, you restore the memory, virtual disks and all settings of the virtual machine to the state they were in when you took the snapshot.";
$_LANG['firewall']['labelDelete'] = 'Delete: ';
$_LANG['disks']['labelDelete'] = 'Delete: ';


$_LANG['home']['description'] = 'Below you can find the list of currently created servers along with their statuses and access to basic actions.';
$_LANG['details']['description'] = 'View server details and the resource usage.';
$_LANG['task']['show_details'] = 'Show Details';
$_LANG['task']['error_details'] = 'Error Details';
$_LANG['panel']['additionals'] = 'Additional Tools';
$_LANG['panel']['scheduledTask'] = 'Scheduled Task';

$_LANG['logs']['description'] = 'Scheduled tasks allow you to view details and the current status of each task.';

$_LANG['CAPages']['home']['stopped'] = 'Stopped';
$_LANG['CAPages']['home']['running'] = 'Running';

$_LANG['kvm_ostype'] = array(
    'other' => 'Unspecified OS',
    'wxp' => 'Microsoft Windows XP',
    'w2k' => 'Microsoft Windows 2000',
    'w2k3' => 'Microsoft Windows 2003',
    'w2k8' => 'Microsoft Windows 2008',
    'wvista' => 'Microsoft Windows Vista',
    'win7' => 'Microsoft Windows 7',
    'win8' => 'Microsoft Windows 8/2012',
    'l24' => 'Linux 2.4 Kernel',
    'l26' => 'Linux 2.6/3.X Kernel'
);
$_LANG['snapshots']['active'] = "Active";
$_LANG['snapshots']['disabled'] = "Disabled";

$_LANG['CAPages']['manageVM']['Boot Order has been successfully changed'] = 'The boot order has been changed successfully';
$_LANG['CAPages']['manageVM']['Edit: Boot Order'] = 'Edit Boot Order';
$_LANG['CAPages']['manageVM']['Edit: CD/DVD'] = 'Edit CD/DVD';
$_LANG['CAPages']['manageVM']['Image File'] = 'Image File';
$_LANG['CAPages']['manageVM']['ISO Image has been successfully changed'] = 'The ISO image has been changed successfully';
$_LANG['CAPages']['manageVM']['Saving changes will reboot the VM'] = 'Saving changes will reboot the virtual machine.';
$_LANG['CAPages']['disks']['Adding, Editing or Removing Disk will reboot the VM'] = 'Adding, editing or removing disk will reboot the virtual machine.';
$_LANG['CAPages']['home']['Server has been successfully added'] = 'The server has been added successfully';
$_LANG['CAPages']['home']['Private Network  Management'] = 'Private Network Management';
$_LANG['CAPages']['privateNetwork']['Private Network  Management'] = 'Private Network Management';
$_LANG['CAPages']['privateNetwork']['description'] = 'Below you can find the list of currently created private networks along with their details and access to basic actions.';
$_LANG['CAPages']['privateNetwork']['Name'] = 'Name';
$_LANG['CAPages']['privateNetwork']['VLAN Tag'] = 'VLAN Tag';
$_LANG['CAPages']['privateNetwork']['VMs'] = 'VMs';
$_LANG['CAPages']['privateNetwork']['Actions'] = 'Actions';


$_LANG['Search'] = 'Search';
$_LANG['No Available'] = 'Not Available';
$_LANG['No Available Info'] = "";
$_LANG['Previous'] = 'Previous';
$_LANG['Next'] = 'Next';
$_LANG['Save Changes'] = 'Save Changes';
$_LANG['Close'] = 'Close';

$_LANG['CAPages']['privateNetwork']['Add Private Network'] = 'Add Private Network';
$_LANG['CAPages']['privateNetwork']['New Private Network'] = 'New Private Network';
$_LANG['CAPages']['privateNetwork']['Save Changes'] = 'Save Changes';
$_LANG['CAPages']['privateNetwork']['Close'] = 'Close';
$_LANG['CAPages']['privateNetwork']['Private network %s has been added'] = 'The private network %s has been added successfully';
$_LANG['CAPages']['privateNetwork']['Delete:'] = 'Delete:';
$_LANG['CAPages']['privateNetwork']['delete_entery'] = 'Are you sure that you want to delete this entry from the network list? ';
$_LANG['CAPages']['privateNetwork']['Delete'] = 'Delete';
$_LANG['CAPages']['privateNetwork']['Private network %s has been delted'] = 'The private network %s has been deleted successfully';
$_LANG['CAPages']['privateNetwork']['Edit:'] = 'Edit:';
$_LANG['CAPages']['privateNetwork']['Private network %s has been updated'] = 'The private network %s has been updated successfully';
$_LANG['CAPages']['privateNetwork']['VM'] = 'VM';
$_LANG['CAPages']['privateNetwork']['IP'] = 'IP';

$_LANG['CAPages']['home']['Templates'] = 'Templates';
$_LANG['CAPages']['templates']['Templates'] = 'Templates';
$_LANG['CAPages']['templates']['description'] = 'Below you can find the list of currently created templates along with their details and access to basic actions.';
$_LANG['CAPages']['templates']['Add Template'] = 'Add Template';
$_LANG['CAPages']['templates']['Server will be converted to a template'] = 'The server will be converted to a template';
$_LANG['CAPages']['templates']['Server'] = 'Server';
$_LANG['CAPages']['templates']['Description'] = 'Description';
$_LANG['CAPages']['templates']['New template'] = 'New Template';
$_LANG['CAPages']['templates']['Server %s has been converted to template'] = 'The server %s has been successfully converted to a template';
$_LANG['CAPages']['templates']['Name'] = 'Name';
$_LANG['CAPages']['templates']['Actions'] = 'Actions';
$_LANG['Delete:'] = 'Delete:';
$_LANG['CAPages']['templates']['delete_entery'] = 'Are you sure that you want to delete this entry from the templates list?';
$_LANG['Delete'] = 'Delete';
$_LANG['CAPages']['templates']['Server %s has been delted'] = 'The server %s has been deleted successfully';
$_LANG['Edit:'] = 'Edit:';
$_LANG['CAPages']['templates']['Server %s has been updated'] = 'The server %s has been updated successfully';
$_LANG['CAPages']['templates']['You server list is empty. Create server first.'] = 'Your list of servers is empty. You need to create the server first.';
$_LANG['CAPages']['privateNetwork']['Edit'] = 'Edit';


$_LANG['cloud']['burst'] = 'Burst';
$_LANG['cloud']['dedicated'] = 'Dedicated';
$_LANG['CAPages']['home']['Disabled'] = 'Disabled';
$_LANG['You are not able to set %s MB of memory. Memory available: %s MB'] = 'You are not able to set %s MB of memory. Memory available: %s MB';
$_LANG['You cannot set %s CPU sockets, it exceeds allowed number of CPU cores: %s'] = 'You are not able to set %s CPU sockets, it exceeds the allowed number of CPU cores: %s';
$_LANG['Select one addresses of IPv4'] = 'Select the IPv4 address';
$_LANG['Hostname is required'] = 'The hostname is required';
$_LANG['Password is required'] = 'The password is required';
$_LANG['Password is too short'] = 'The password is too short';
$_LANG['You are not able to set %s CPU cores. CPU cores available: %s (per socket)'] = 'You are not able to set %s CPU cores. CPU cores available: %s (per socket)';
$_LANG['You are not able to set %s CPU cores. CPU cores available: %s'] = 'You are not able to set %s CPU cores. CPU cores available: %s';
$_LANG['You are not able to set %s of CPU sockets. Amount CPU sockets: %s'] = 'You are not able to set %s of CPU sockets. CPU sockets available: %s';
$_LANG['You are not able to set %s CPU weight. CPU weight available: %s'] = 'You are not able to set %s CPU weight. CPU weight available: %s';
$_LANG['You are not able to set %s GB of disk space. Space available: %s GB'] = 'You are not able to set %s GB of disk space. Disk space available: %s GB';
$_LANG['You are not able to set %s of IPv4 addresses. IPs available: %s'] = 'You are not able to set %s of IPv4 addresses. IPs available: %s';
$_LANG['You are not able to set %s of IPv6 addresses. IPs available: %s'] = 'You are not able to set %s of IPv6 addresses. IPs available: %s';
$_LANG['Name Server value "%s" does not look like a valid IP Address'] = 'The name server value "%s" does not seem to be a valid IP address';
$_LANG['You are not able to set % of SWAP. Amount SWAP: %s'] = 'You are not able to set % of SWAP. SWAP available: %s';
$_LANG['Hostname \'%s\' is invalid'] = 'The hostname \'%s\' is invalid';
$_LANG['Server creating in progress...'] = 'The server creation is in progress';
$_LANG['Scheduled Task (\'createVm\') already exists'] = 'The scheduled task (\'createVm\') already exists';
$_LANG['CPU Limit'] = 'CPU Limit';
$_LANG['CAPages']['backup']['Date'] = 'Date';
$_LANG['CAPages']['backup']['Restoring VM in progress'] = 'The VM restoring is in progress';
$_LANG['CAPages']['taskHistory']['Error'] = 'Error';
$_LANG['Firewall Options'] = 'Firewall Options';
$_LANG['CAPages']['FirewallOptions']['Firewall Options'] = 'Firewall Options';
$_LANG['CAPages']['FirewallOptions']['Define firewall options for your VPS.'] = 'Define firewall options for your VPS.';
$_LANG['CAPages']['FirewallOptions']['Edit'] = 'Edit';
$_LANG['CAPages']['FirewallOptions']['Enable Firewall'] = 'Enable Firewall';
$_LANG['CAPages']['FirewallOptions']['Enable DHCP'] = 'Enable DHCP';
$_LANG['CAPages']['FirewallOptions']['Enable NDP'] = 'Enable NDP';
$_LANG['CAPages']['FirewallOptions']['Allow Router Advertisement'] = 'Allow Router Advertisement';
$_LANG['CAPages']['FirewallOptions']['MAC Filter'] = 'MAC Filter';
$_LANG['CAPages']['FirewallOptions']['IP Filter'] = 'IP Filter';
$_LANG['CAPages']['FirewallOptions']['log_level_in'] = 'log_level_in';
$_LANG['CAPages']['FirewallOptions']['log_level_out'] = 'log_level_out';
$_LANG['CAPages']['FirewallOptions']['Input Policy'] = 'Input Policy';
$_LANG['CAPages']['FirewallOptions']['Output Policy'] = 'Output Policy';
$_LANG['CAPages']['FirewallOptions']['No'] = 'No';
$_LANG['CAPages']['FirewallOptions']['Yes'] = 'Yes';
$_LANG['CAPages']['FirewallOptions']['nolog'] = 'nolog';
$_LANG['CAPages']['FirewallOptions']['DROP'] = 'DROP';
$_LANG['CAPages']['FirewallOptions']['ACCEPT'] = 'ACCEPT';
$_LANG['CAPages']['FirewallOptions']['Edit: Firewall Options'] = 'Edit Firewall Options';
$_LANG['CAPages']['FirewallOptions']['Save Changes'] = 'Save Changes';
$_LANG['CAPages']['FirewallOptions']['Close'] = 'Close';
$_LANG['CAPages']['FirewallOptions']['Firewall Options have been updated'] = 'The firewall options have been updated successfully';
$_LANG['CAPages']['FirewallOptions']['err'] = 'err';
$_LANG['CAPages']['FirewallOptions']['info'] = 'info';
$_LANG['CAPages']['FirewallOptions']['REJECT'] = 'REJECT';
$_LANG['CAPages']['FirewallOptions']['crit'] = 'crit';
$_LANG['CAPages']['FirewallOptions']['warning'] = 'warning';
$_LANG['CAPages']['FirewallOptions']['alert'] = 'alert';
$_LANG['CAPages']['FirewallOptions']['emerg'] = 'emerg';
$_LANG['CAPages']['FirewallOptions']['debug'] = 'debug';
$_LANG['CAPages']['disks']['No']='No';
$_LANG['CAPages']['disks']['Yes']='Yes';
$_LANG['CAPages']['manageVM']['Downgrade the KVM disk is not supported']='KVM disk downgrading is not supported';
$_LANG['CAPages']['manageVM']['You are not able to downgrade IP Addresses']='You are not able to downgrade the IP addresses';
$_LANG['CAPages']['manageVM']['Hostname is required']='The hostname is required';
$_LANG['CAPages']['home']['CPU Limit']='CPU Limit';
$_LANG['CAPages']['home']['VCPUs']='VCPUs';
$_LANG['You are not able to set %s of VCPUs. VCPUs available: %s']='You are not able to set %s of VCPUs. VCPUs available: %s';
$_LANG['You are not able to set %s of CPU Limit. CPU Limit available: %s']='You are not able to set %s of CPU limit. CPU limit available: %s';
$_LANG['CAPages']['home']['Server creating in progress...']='The server creation is in progress';
$_LANG['CAPages']['home']["Scheduled Task ('createVm') already exists"]="The scheduled task ('createVm') already exists";
$_LANG['CAPages']['manageVM']['CPU Limit']='CPU Limit';
$_LANG['CAPages']['manageVM']['VCPUs']='VCPUs';
$_LANG['CAPages']['home']['OS Template require disk size %s GB']='The OS template requires %s GB of disk size'; 
$_LANG['CAPages']['home']['SSH Key\'s']='SSH Keys';
$_LANG['CAPages']['home']['Generate private & public key.']='Generate the private and public key.';
$_LANG['CAPages']['manageVM']['SSH Key\'s']='SSH Keys';
$_LANG['CAPages']['manageVM']['Download Private Key']='Download Private Key';
$_LANG['CAPages']['manageVM']['Download Public Key']='Download Public Key';
$_LANG['CAPages']['manageVM']['SSH Key you can download only once']='You can download the SSH key only once';
$_LANG['CAPages']['manageVM']['Download']='Download';
$_LANG['CAPages']['home']['SSH Public Key File']='SSH Public Key File';
$_LANG['CAPages']['home']['SSH public key is invalid']='The SSH public key is invalid';
$_LANG['CAPages']['home']['Remove']='Remove';
$_LANG['CAPages']['reinstall']['Provide OS Template.']='Provide OS Template';
$_LANG['CAPages']['reinstall']['SSH Key\'s']='SSH Keys';
$_LANG['CAPages']['reinstall']['Generate private & public key.']='Generate the private and public key.';
$_LANG['CAPages']['reinstall']['SSH Public Key File']='SSH Public Key File';
$_LANG['CAPages']['reinstall']['Reinstall task currently in progress...']='The reinstallation is in progress';
$_LANG['CAPages']['reinstall']['OS Template require disk size %s GB']='The OS template requires %s GB of disk size'; 
$_LANG['CAPages']['home']['Scheduled Task (\'createVm\') already exist']='The scheduled task (\'createVm\') already exists';
$_LANG['CAPages']['home']['Location']='Location';
$_LANG['proxmox']='proxmox';
$_LANG['CAPages']['home']['Building']='Building';
$_LANG['Virtual Server \'%s\' is not built yet']='The virtual server \'%s\' has not been built yet';
$_LANG['Virtual Server \'%s\' is begin reinstall.']= 'The virtual server \'%s\' is being reinstalled';
$_LANG['CAPages']['reinstall']['Password is too short']='The password is too short';
$_LANG['CAPages']['manageVM']['Downgrade IPv4 is not supported']='IPv4 downgrading is not supported';
$_LANG['CAPages']['manageVM']['Downgrade IPv6 is not supported']='IPv6 downgrading is not supported';
$_LANG['CAPages']['home']['Select one addresses of IPv4']='Select the IPv4 address';
$_LANG['CAPages']['home']['Hostname is required']='The hostname is required';
$_LANG['CAPages']['home']['Password is required']='The password is required';
$_LANG['You are not able to set %s of SWAP. Amount SWAP: %s'] ='You are not able to set %s of SWAP. SWAP available: %s';
$_LANG['CAPages']['manageVM']['Downgrade the disk is not supported']='Disk downgrading is not supported';
$_LANG["Do you really want to boot?"]="Are you sure that you want to boot the server?";
$_LANG["Do you really want to reboot?"]="Are you sure that you want to reboot the server?";
$_LANG["Do you really want to stop?"]="Are you sure that you want to stop the server?";
$_LANG["Do you really want to shutdown?"]="Are you sure that you want to shut down the server?";
$_LANG['CAPages']['manageVM']['resizeDiskWarning'] = "If the virtual machine is upgraded by changing the disk size to a larger one, the 'Resize Disk Space' option will automatically increase the size of the last partition in that disk with the newly added value.
The option deletes the current partition table, then creates a new one according to the new disk size and reboots the virtual machine. Please note that in case of any failure, all data will be lost on the resized partition.";
$_LANG["Firewall Options"]="Firewall Options";
$_LANG['CAPages']['reinstall']['Type']='Type';
$_LANG['CAPages']['reinstall']['KVM Template']='KVM Template';
$_LANG['CAPages']['reinstall']['ISO Image']='ISO Image';
$_LANG['Installation is now processing. The login information will be available in the noVNC console.']='The installation is in progress. The login information will be available in the noVNC console.';
$_LANG['CAPages']['reinstall']['Provide OS Template']='Provide OS Template';
$_LANG['Rebuild VM in progress. Please try again later.']='The VM rebuilding is in progress. Please try again later.';
$_LANG['CAPages']['reinstall']['kvmTemplate']['desription'] ='Select this option if you want to install the OS automatically.';
$_LANG['CAPages']['reinstall']['isoImage']['desription']='Select this option if you want to install the OS manually.';
$_LANG['CAPages']['reinstall']['Reinstall']='Reinstall';
$_LANG['CAPages']['MountPoints']['Disks']='Disks';
 $_LANG['CAPages']['MountPoints']['description']='View and manage the hard disk within defined limits. Any additional disk can be removed at will.';
$_LANG['CAPages']['MountPoints']['Adding, editing or removing disk will reboot the VM.']='Adding, editing or removing disk will reboot the virtual machine.';
$_LANG['CAPages']['MountPoints']['Name']='Name';

$_LANG['CAPages']['MountPoints']['Id']                                                                  = 'ID';
$_LANG['CAPages']['MountPoints']['Path']                                                                = 'Path';
$_LANG['CAPages']['MountPoints']['Backup']                                                              = 'Backup';
$_LANG['CAPages']['MountPoints']['Size']                                                                = 'Size';
$_LANG['CAPages']['MountPoints']['Yes']                                                                 = 'Yes';
$_LANG['CAPages']['MountPoints']['No']                                                                  = 'No';
$_LANG['CAPages']['MountPoints']['Actions'] ='Actions';
$_LANG['CAPages']['MountPoints']['Size (GB)'] = 'Size (GB)';
$_LANG['CAPages']['MountPoints']['Delete']='Delete';
$_LANG['CAPages']['MountPoints']['confirm']['delete'] ='Are you sure that you want to delete this hard disk?';
$_LANG['CAPages']['MountPoints']['Delete:']='Delete:';
$_LANG['CAPages']['MountPoints']['Close']='Close';
$_LANG['CAPages']['MountPoints']['Edit Disk']='Edit Disk';
$_LANG['CAPages']['MountPoints']['Save Changes']='Save Changes';
$_LANG['CAPages']['MountPoints']['Close']='Close';
$_LANG['CAPages']['MountPoints']['Add New']='Add New';
$_LANG['CAPages']['MountPoints']['Edit']='Edit';
$_LANG['CAPages']['MountPoints']['Add']='Add';
$_LANG['CAPages']['MountPoints']['New Disk']          = 'New Disk';
$_LANG['CAPages']['MountPoints']['/some/path']        = '/some/path';
$_LANG['Unable to shrink disk size ']                 = 'Unable to shrink disk size ';
$_LANG['CAPages']['MountPoints']['Disk 1']            = 'Disk 1';
$_LANG['CAPages']['MountPoints']['Disk 2']            = 'Disk 2';
$_LANG['CAPages']['MountPoints']['Disk 3']            = 'Disk 3';
$_LANG['CAPages']['MountPoints']['Disk 4']            = 'Disk 4';
$_LANG['CAPages']['MountPoints']['Disk 5']            = 'Disk 5';
$_LANG['CAPages']['MountPoints']['Disk 6']            = 'Disk 6';
$_LANG['CAPages']['MountPoints']['Disk 7']            = 'Disk 7';
$_LANG['CAPages']['MountPoints']['Disk 8']='Disk 8';
$_LANG['CAPages']['MountPoints']['Disk 9']='Disk 9';
$_LANG['CAPages']['MountPoints']['Disk 10']='Disk 10';
$_LANG['CAPages']['home']['Password is too short']='The password is too short';
$_LANG['CPU Usage']                 = 'CPU Usage';
$_LANG['Memory Usage']                 = 'Memory Usage';
$_LANG['Total']                 = 'Total';
$_LANG['Net In']                 = 'Net In';
$_LANG['Net Out']                 = 'Net Out';
$_LANG['Disk Read']                 = 'Disk Read';
$_LANG['Disk Write']                 = 'Disk Write';
$_LANG['Confirmation']  ='Confirmation';
$_LANG['Yes']  ='Yes';
$_LANG['No'] = 'No';
$_LANG['CAPages']['home']['DNS Domain']='DNS Domain';
$_LANG['CAPages']['home']['User']='User';
$_LANG['CAPages']['home']['User Password']='User Password';
$_LANG['Password has been changed']='Password has been changed';
$_LANG['DNS Domain \'%s\' is invalid'] = 'The DNS Domain \'%s\' is invalid';